### ISSUE TITLE
TabTip crash when change input method

### ISSUE THREAD

**Issue by zzczzc004** [maximcus/WPFTabTip#11]
Here is the operation, http://recordit.co/vKmrrL3QGT.
In window event viewer, there show the TabTip was crashed.
Error Application Name: TabTip.exe, Version: 10.0.14393.0, Timestamp: 0x57899a67
Error Module Name: CRYPT32.dll, Version: 10.0.14393.351, Timestamp: 0x5801a419
Exception code: 0xc0000005
Error offset: 0x000000000004f60e
Error Process ID: 0x5b34
Error Application startup time: 0x01d27f56c4e42989
Error Application path: C: \ Program Files \ Common Files \ microsoft shared \ ink \ TabTip.exe
Error Module Path: C: \ WINDOWS \ System32 \ CRYPT32.dll

**Comment by maximcus** [comment]
@zzczzc004 , what version of Windows do you use? Are you using latest version of WPFTabTip? and please check if "C: \ Program Files \ Common Files \ microsoft shared \ ink \ TabTip.exe" path is correct. Also i do not really understood your actions from recording. Can you explain in steps how can i reproduce that crash?

**Comment by zzczzc004** [comment]
I use Win 10 Professional version 1607. 
Lastest version of WPFTabTip. 
The path is correct.
I open the UITest.exe, click the TextBox and the TabTip open, then I changed input method from handing write to keyboard and change back. TabTip may crash and window event viewer has the record. The Exception code has 0xc000041d and 0xc0000005.

**Comment by maximcus** [comment]
resolved with #13
