### ISSUE TITLE
Validation.ErrorTemplate don't move with the view in maximize window

### ISSUE THREAD

**Issue by zzczzc004** [maximcus/WPFTabTip#12]
In my application, I binding **TextBox.Text** with the property in ViewModel and do some validation. When validation is failed, the textbox show the prompt accroding to the **Validation.ErrorTemplate**. But when the window is maximize and textbox already show the validation error prompt . When I click the textbox again. The tabtip opens and the view moves, but the validation error prompt don't move.
I find this problem only appear in **maximize the windows**.

**Comment by maximcus** [comment]
Interesting, @zzczzc004 have a look at WPFTabTip. AnimationHelper.GetRootVisualForAnimation method. This method decides will `Window` or it's `Content` be moved. If i am not mistaken, then validation message is not in the `Content` visual tree, and you need to change this logic.

**Comment by zzczzc004** [comment]
Thank you for showing me the way. I find the adorner which used for showing validation message has higher level than the rootWindow.Content in visual tree. That is why the problem occurred. 
I solve this problem by add a helper method to find the window's first visual node in the child instead of using rootWindow.Content when the window is maximized. This problem troubles me these days. Thank you very much.

**Comment by maximcus** [comment]
You welcome @zzczzc004, but if your solution can help other people then do create pull request to resolve this issue.

**Comment by zzczzc004** [comment]
My current work condition is not convenient to make the pull request, I will do it later.
