### ISSUE TITLE
Ignore a given textbox

### ISSUE THREAD

**Issue by fredericoregateiro** [maximcus/WPFTabTip#15]
Hello,

Is there a way to ignore only a given textbox?

Thanks

**Comment by maximcus** [comment]
No, unfortunately, there is no way to ignore a single text box.

You can, however, create your own text box control (just inherit from the TextBox control, and do nothing else). With that, you will be able to specify on which text boxes you need TabTip and on which you do not.

**Comment by fredericoregateiro** [comment]
ok, thanks
