### ISSUE TITLE
Bind To Textbox - but only if ReadOnly = false

### ISSUE THREAD

**Issue by Cocotus** [maximcus/WPFTabTip#19]
I use this library and bound the keyboard popup to textboxes- works great so far (using the code fix for Windows10) Is there any way to avoid the keyboard popping up on a ReadOnly textbox? Right now it will always show the keyboard, even though the user isn't allowed to write any text in it. Is there a way to only display the keyboard if textboxes are not readonly?

**Comment by maximcus** [comment]
Do your ReadOnly TextBoxes change to an active state (ready for input) at some point?

**Comment by Cocotus** [comment]
Hi, sorry for late reply - I fixed the "problem" myself by adding property "IsHitTestVisible" = false  to all my readonly textboxes in my XAML files and it works as expected 👍
