### ISSUE TITLE
Problem with lost focus

### ISSUE THREAD

**Issue by Wardog33** [maximcus/WPFTabTip#21]
Hello,

I am creating a custom control in C# WPF and am using the WPFTabTip in my project.
I have bound all textboxes in the startup logic and for the most part my application works fine if there is just one or two controls on a page. For my custom control I have a dynamic number of textboxes that are created dynamically and I am setting the InputScope to "Number" for all of them as I have a need to enter only numeric info in each textbox.

When setting focus on the first text box it works just fine. When I select the next textbox under it, I see the alpha keyboard load, then very quickly goes to the number keyboard. Selecting the text box under that does not close and reopen the keyboard, it stays open and is alphanumeric keys. Any other selection the keyboard stays up and is not respecting the InputScope and does not close the keyboard when losing focus.

If I manually close the keyboard after every selection it works just fine, but I don't want my users to have to do that. Either a manual close of the keyboard when focus is lost OR keep the keyboard open and have the keyboard respond to the type of keyboard I need.

I am running Windows 10 as an Operating System and using VS2017 for development.

I also was able to get your application with the UITest and added 8 textboxes to the DialogWindow. I am seeing the exact same behavior. (4 set to InputScope of Number and 4 without). 

Any help would be greatly appreciated as I have a high need to be able to use the onboard keyboard that comes with Windows 10 AND be able to dictate which kind of keyboard is needed based on input.

Thanks much,
James

**Comment by Wardog33** [comment]
Well it seems that this erratic behavior is found in Windows 10 on my desktop. When I published the application to the SurfacePro also running Windows 10 it worked flawlessly. Not sure I have an answer as to why, but so far I am very happy with the results. James

**Comment by maximcus** [comment]
FYI InputScope and changing of virtual keyboard layout are built into WPF. WPFTabTip has nothing to do with that. Also, I never used WPFTabTip on Windows 10, but I have heard that some people have issues there. I no longer work with WPF, so this project is on life support for the time being.
