### ISSUE TITLE
Add support for ignoring multiple instances of keyboards

### ISSUE THREAD

**Issue by wldevries** [maximcus/WPFTabTip#7]
We're using Surface Pro 4 devices and by default they have multiple hardwired keyboards. We'd like to ignore those, but WPFTabTip only allows to ignore just one.

The Surface Pro 4 has the following keyboards:
- HID Keyboard Device (hardware buttons such as volume and windows button)
- Surface Pen Click Filter (software keyboard for buttons on the pen that is shipped with the tablet)

**Comment by maximcus** [comment]
Closing with 6dcdd6a8fae94889fd98d317ebbee25ef4356281 and d8afa3a40aec022c933f346b04eeb4033e3e989b
